import { useEffect, useState } from "react";
import { dataService, type Memory, type Project } from "../services/dataService";
import EntityModal from "./EntityModal";
export default function MemoriesScreen() {
  const [items, setItems] = useState<Memory[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Partial<Memory> | null>(null);
  const reload = async () => { const [memories, savedProjects] = await Promise.all([dataService.list<Memory>("memories"), dataService.list<Project>("projects")]); setItems(memories); setProjects(savedProjects); };
  useEffect(() => { void reload(); }, []);
  const save = async () => { if (!editing?.content?.trim()) return; const changes = { content: editing.content.trim(), category: editing.category?.trim() || "Geral", projectId: editing.projectId || null }; if (editing.id) await dataService.update("memories", editing.id, changes); else await dataService.create("memories", changes); setEditing(null); await reload(); };
  const filtered = items.filter(x => `${x.content} ${x.category}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="flex flex-col h-full flex-1 overflow-hidden"><header className="px-6 py-4" style={{ background: "#171923", borderBottom: "1px solid #252840" }}><div className="flex items-center mb-4"><div><h1 className="text-lg font-semibold">Memórias</h1><p className="text-xs" style={{ color: "#9296A8" }}>{items.length} armazenadas localmente</p></div><button onClick={() => setEditing({ category: "Geral" })} className="noir-primary-button ml-auto">+ Nova memória</button></div><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar memórias..." className="noir-input w-full" /></header><main className="flex-1 overflow-y-auto p-6"><div className="grid gap-3" style={{ gridTemplateColumns: "repeat(auto-fill,minmax(280px,1fr))" }}>{filtered.map(memory => <article key={memory.id} className="noir-card"><span className="text-xs" style={{ color: "#a78bfa" }}>{memory.category}{memory.projectId ? ` · ${projects.find(p => p.id === memory.projectId)?.name ?? "Projeto"}` : ""}</span><p className="text-sm my-4 whitespace-pre-wrap">{memory.content}</p><div className="flex gap-2"><button onClick={() => setEditing(memory)} className="noir-secondary-button">Editar</button><button onClick={async () => { if (window.confirm("Excluir esta memória?")) { await dataService.remove("memories", memory.id); await reload(); } }} className="noir-danger-button">Excluir</button></div></article>)}</div></main>
    {editing && <EntityModal title={editing.id ? "Editar memória" : "Nova memória"} onClose={() => setEditing(null)} onSubmit={() => void save()}><textarea autoFocus className="noir-input w-full min-h-32" value={editing.content ?? ""} onChange={e => setEditing({ ...editing, content: e.target.value })} placeholder="Conteúdo"/><input className="noir-input w-full" value={editing.category ?? ""} onChange={e => setEditing({ ...editing, category: e.target.value })} placeholder="Categoria"/><select className="noir-input w-full" value={editing.projectId ?? ""} onChange={e => setEditing({ ...editing, projectId: e.target.value || undefined })}><option value="">Sem projeto</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></EntityModal>}
  </div>;
}
