import { useEffect, useState } from "react";
import { dataService, type Memory } from "../services/dataService";

export default function MemoriesScreen() {
  const [memories, setMemories] = useState<Memory[]>([]); const [search, setSearch] = useState("");
  const reload = () => dataService.list<Memory>("memories").then(setMemories);
  useEffect(() => { void reload(); }, []);
  const create = async () => { const content = window.prompt("Conteúdo da memória:")?.trim(); if (!content) return; const category = window.prompt("Categoria:", "Geral")?.trim() || "Geral"; await dataService.create<Memory>("memories", { content, category }); await reload(); };
  const edit = async (memory: Memory) => { const content = window.prompt("Conteúdo:", memory.content)?.trim(); if (!content) return; const category = window.prompt("Categoria:", memory.category)?.trim() || memory.category; await dataService.update<Memory>("memories", memory.id, { content, category }); await reload(); };
  const remove = async (id: string) => { if (window.confirm("Excluir esta memória?")) { await dataService.remove("memories", id); await reload(); } };
  const filtered = memories.filter(memory => `${memory.content} ${memory.category}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="flex flex-col h-full flex-1 overflow-hidden"><header className="px-6 py-4" style={{ background: "#171923", borderBottom: "1px solid #252840" }}><div className="flex items-center mb-4"><div><h1 className="text-lg font-semibold">Memórias</h1><p className="text-xs" style={{ color: "#9296A8" }}>{memories.length} armazenadas localmente</p></div><button onClick={create} className="noir-primary-button ml-auto">+ Nova memória</button></div><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar memórias..." className="noir-input w-full" /></header><main className="flex-1 overflow-y-auto p-6"><div className="grid gap-3" style={{ gridTemplateColumns: "repeat(auto-fill,minmax(280px,1fr))" }}>{filtered.map(memory => <article key={memory.id} className="noir-card"><span className="text-xs px-2 py-1 rounded-full" style={{ background: "#7B61FF18", color: "#a78bfa" }}>{memory.category}</span><p className="text-sm my-4 whitespace-pre-wrap">{memory.content}</p><div className="flex gap-2"><button onClick={() => edit(memory)} className="noir-secondary-button">Editar</button><button onClick={() => remove(memory.id)} className="noir-danger-button">Excluir</button></div></article>)}</div>{!filtered.length && <p className="text-center mt-16 text-sm" style={{ color: "#9296A8" }}>Nenhuma memória encontrada.</p>}</main></div>;
}
