import { useCallback, useEffect, useState } from "react";
import { dataService, type Note, type Project, type Task } from "../services/dataService";
import type { NotesTab } from "../App";
import EntityModal from "./EntityModal";
interface Props { initialTab: NotesTab; createRequest: number; onTabChange: (t: NotesTab) => void; onCreateRequestHandled: () => void }
type Editing = ({ kind: "notes" } & Partial<Note>) | ({ kind: "tasks" } & Partial<Task>);
export default function NotesScreen({ initialTab: tab, createRequest, onTabChange, onCreateRequestHandled }: Props) {
  const [notes, setNotes] = useState<Note[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [search, setSearch] = useState(""); const [projectFilter, setProjectFilter] = useState(""); const [taskFilter, setTaskFilter] = useState("all"); const [editing, setEditing] = useState<Editing | null>(null);
  const reload = useCallback(async () => { const [n, t, p] = await Promise.all([dataService.list<Note>("notes"), dataService.list<Task>("tasks"), dataService.list<Project>("projects")]); setNotes(n); setTasks(t); setProjects(p); }, []);
  useEffect(() => { void reload(); }, [reload]); useEffect(() => { if (createRequest) { onCreateRequestHandled(); onTabChange("notes"); setEditing({ kind: "notes" }); } }, [createRequest, onCreateRequestHandled, onTabChange]);
  const save = async () => { if (!editing?.title?.trim()) return; if (editing.kind === "notes") { const changes = { title: editing.title.trim(), content: editing.content ?? "", projectId: editing.projectId || null }; editing.id ? await dataService.update("notes", editing.id, changes) : await dataService.create("notes", changes); } else { const changes = { title: editing.title.trim(), description: editing.description ?? "", completed: editing.completed ?? false, dueDate: editing.dueDate || null, projectId: editing.projectId || null }; editing.id ? await dataService.update("tasks", editing.id, changes) : await dataService.create("tasks", changes); } setEditing(null); await reload(); };
  const visibleNotes = notes.filter(x => (!projectFilter || x.projectId === projectFilter) && `${x.title} ${x.content}`.toLowerCase().includes(search.toLowerCase()));
  const visibleTasks = tasks.filter(x => (!projectFilter || x.projectId === projectFilter) && (taskFilter === "all" || (taskFilter === "done") === x.completed) && `${x.title} ${x.description ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="flex flex-col h-full flex-1 overflow-hidden"><header className="px-6 py-4" style={{ background: "#171923", borderBottom: "1px solid #252840" }}><div className="flex gap-2 mb-4"><button onClick={() => onTabChange("notes")} className={tab === "notes" ? "noir-primary-button" : "noir-secondary-button"}>Notas</button><button onClick={() => onTabChange("tasks")} className={tab === "tasks" ? "noir-primary-button" : "noir-secondary-button"}>Tarefas</button><button onClick={() => setEditing(tab === "notes" ? { kind: "notes" } : { kind: "tasks", completed: false })} className="noir-primary-button ml-auto">+ Novo</button></div><div className="flex gap-2"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Pesquisar..." className="noir-input flex-1"/><select className="noir-input" value={projectFilter} onChange={e => setProjectFilter(e.target.value)}><option value="">Todos os projetos</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>{tab === "tasks" && <select className="noir-input" value={taskFilter} onChange={e => setTaskFilter(e.target.value)}><option value="all">Todas</option><option value="open">Pendentes</option><option value="done">Concluídas</option></select>}</div></header><main className="flex-1 overflow-y-auto p-6"><div className="grid gap-3" style={{ gridTemplateColumns: "repeat(auto-fill,minmax(280px,1fr))" }}>{tab === "notes" ? visibleNotes.map(x => <article className="noir-card" key={x.id}><h3 className="font-semibold">{x.title}</h3><p className="text-xs" style={{ color: "#a78bfa" }}>{projects.find(p => p.id === x.projectId)?.name}</p><p className="text-sm my-3 whitespace-pre-wrap">{x.content}</p><button className="noir-secondary-button" onClick={() => setEditing({ kind: "notes", ...x })}>Editar</button> <button className="noir-danger-button" onClick={async () => { if (window.confirm("Excluir este item?")) { await dataService.remove("notes", x.id); await reload(); } }}>Excluir</button></article>) : visibleTasks.map(x => <article className="noir-card" key={x.id}><label className="flex gap-2"><input type="checkbox" checked={x.completed} onChange={async () => { await dataService.update("tasks", x.id, { completed: !x.completed }); await reload(); }}/><span className={x.completed ? "line-through opacity-60" : ""}>{x.title}</span></label><p className="text-sm my-3">{x.description}</p>{x.dueDate && <p className="text-xs mb-3" style={{ color: "#9296A8" }}>Prazo: {x.dueDate}</p>}<button className="noir-secondary-button" onClick={() => setEditing({ kind: "tasks", ...x })}>Editar</button> <button className="noir-danger-button" onClick={async () => { if (window.confirm("Excluir este item?")) { await dataService.remove("tasks", x.id); await reload(); } }}>Excluir</button></article>)}</div></main>
    {editing && <EntityModal title={editing.id ? "Editar item" : "Novo item"} onClose={() => setEditing(null)} onSubmit={() => void save()}><input autoFocus required className="noir-input w-full" value={editing.title ?? ""} onChange={e => setEditing({ ...editing, title: e.target.value } as Editing)} placeholder="Título"/><textarea className="noir-input w-full min-h-28" value={(editing.kind === "notes" ? editing.content : editing.description) ?? ""} onChange={e => setEditing(editing.kind === "notes" ? { ...editing, content: e.target.value } : { ...editing, description: e.target.value })} placeholder={editing.kind === "notes" ? "Conteúdo" : "Descrição"}/><select className="noir-input w-full" value={editing.projectId ?? ""} onChange={e => setEditing({ ...editing, projectId: e.target.value || undefined } as Editing)}><option value="">Sem projeto</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>{editing.kind === "tasks" && <input type="date" className="noir-input w-full" value={editing.dueDate ?? ""} onChange={e => setEditing({ ...editing, dueDate: e.target.value })}/>}</EntityModal>}
  </div>;
}
