import { useCallback, useEffect, useState } from "react";
import { AIService } from "../systems/ai/AIService";
import { useSettings } from "../systems/settings/SettingsContext";
import type { AIStatus, OllamaStatus } from "../systems/ai/types";
import { useCharacter } from "../systems/character/CharacterContext";
import { CHARACTER_STATES, type CharacterState } from "../systems/character/noirSprites";
function Toggle({ value, onChange }: { value: boolean; onChange: (v: boolean) => void }) { return <button onClick={() => onChange(!value)} aria-pressed={value} className="w-11 h-6 rounded-full relative" style={{ background: value ? "#7B61FF" : "#252840" }}><span className="absolute top-1 w-4 h-4 rounded-full bg-white transition-all" style={{ left: value ? 24 : 4 }} /></button>; }
function Row({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="flex items-center gap-5 py-4" style={{ borderBottom: "1px solid #252840" }}><div className="flex-1"><p className="text-sm font-medium">{title}</p><p className="text-xs mt-1" style={{ color: "#9296A8" }}>{description}</p></div>{children}</div>; }
const providerLabels = { local: "Local (Ollama)", groq: "Groq", openrouter: "OpenRouter", openai: "OpenAI", mock: "MockProvider" };
const modelFields = { local: "ollamaModel", groq: "groqModel", openrouter: "openRouterModel", openai: "openAIModel" } as const;
export default function SettingsScreen() {
  const { characterState, setCharacterState } = useCharacter();
  const { settings, updateSettings } = useSettings(); const [status, setStatus] = useState<AIStatus | null>(null); const [ollama, setOllama] = useState<OllamaStatus | null>(null); const [shortcut, setShortcut] = useState(""); const [key, setKey] = useState(""); const [webKey, setWebKey] = useState(""); const [webConfigured, setWebConfigured] = useState(false); const [showKey, setShowKey] = useState(false); const [feedback, setFeedback] = useState(""); const [webFeedback, setWebFeedback] = useState(""); const [busy, setBusy] = useState(false);
  const refreshLocal = useCallback(async () => { setBusy(true); try { const result = await AIService.ollamaStatus(); setOllama(result); setStatus(await AIService.status()); } finally { setBusy(false); } }, []);
  useEffect(() => { void AIService.status().then(value => { setStatus(value); if (value.selectedProvider === "local") void refreshLocal(); }); return AIService.onStatusChanged(setStatus); }, [refreshLocal]);
  useEffect(() => { void window.projectNoir?.webSearch.status().then(value => setWebConfigured(value.configured)); }, [settings?.webSearchProvider]);
  useEffect(() => { if (settings) setShortcut(settings.globalShortcut); }, [settings]);
  const action = async (work: () => Promise<unknown>, success: string) => { setBusy(true); setFeedback(""); try { await work(); setStatus(await AIService.status()); setFeedback(success); } catch (e) { setFeedback(e instanceof Error ? e.message : "A operação falhou."); if (settings?.aiProvider === "local") await refreshLocal(); } finally { setBusy(false); } };
  if (!settings) return <div className="grid place-items-center flex-1">Carregando configurações...</div>;
  const provider = settings.aiProvider; const remote = provider === "openai" || provider === "groq" || provider === "openrouter"; const configured = provider === "openai" ? status?.openAIConfigured : provider === "groq" ? status?.groqConfigured : status?.openRouterConfigured; const modelField = provider === "mock" ? null : modelFields[provider];
  const webProvider = settings.webSearchProvider; const webNeedsKey = webProvider !== "wikipedia"; const webProviderLabel = { tavily: "Tavily", serper: "Serper", wikipedia: "Wikipedia", brave: "Brave Search" }[webProvider];
  const localExplanation = ollama?.state === "not-installed" ? "O Ollama não foi encontrado. Instale-o pelo site oficial, inicie o aplicativo e adicione um modelo." : ollama?.state === "server-stopped" ? "O Ollama está instalado, mas o servidor local não respondeu. Abra o Ollama e tente novamente." : ollama?.state === "no-models" ? "Ollama está ativo, mas não há modelos instalados. Instale um modelo manualmente; o Project Noir não fará downloads automáticos." : ollama?.state === "ready" ? "Ollama ativo. As mensagens permanecem neste computador enquanto o fallback estiver desligado." : "Verificando o Ollama…";
  return <div className="flex-1 overflow-y-auto p-5 sm:p-8"><div className="max-w-2xl"><h1 className="text-xl font-semibold">Configurações</h1><p className="text-sm mt-1 mb-6" style={{ color: "#9296A8" }}>Preferências persistentes do Project Noir</p>
    <section className="noir-card mb-4"><h2 className="font-semibold mb-2">Personagem</h2><Row title="Mostrar personagem" description="Exibe a Nyra no painel contextual"><Toggle value={settings.showCharacter} onChange={v => void updateSettings({ showCharacter: v })}/></Row><Row title="Animações" description="Transição entre expressões"><Toggle value={settings.characterAnimations} onChange={v => void updateSettings({ characterAnimations: v })}/></Row><Row title="Expressões automáticas" description="Respostas alteram o estado visual"><Toggle value={settings.automaticExpressions} onChange={v => void updateSettings({ automaticExpressions: v })}/></Row>
      {import.meta.env.DEV && <Row title="Developer · expressão" description="Pré-visualização manual dos 15 recortes da sprite sheet"><select aria-label="Expressão da Nyra" className="noir-input" value={characterState} onChange={event => setCharacterState(event.target.value as CharacterState)}>{CHARACTER_STATES.map(state => <option key={state} value={state}>{state}</option>)}</select></Row>}
    </section>
    <section className="noir-card mb-4"><h2 className="font-semibold mb-2">Windows</h2><Row title="Iniciar com o Windows" description="Desativado por padrão"><Toggle value={settings.launchAtLogin} onChange={v => void updateSettings({ launchAtLogin: v })}/></Row><Row title="Notificações nativas" description="Permite notificações do aplicativo"><Toggle value={settings.notifications} onChange={v => void updateSettings({ notifications: v })}/></Row><Row title="Atalho global" description="Mostra ou oculta a janela"><input className="noir-input w-56" value={shortcut} onChange={e => setShortcut(e.target.value)} onBlur={() => void action(() => updateSettings({ globalShortcut: shortcut.trim() }), "Atalho registrado.")}/></Row></section>
    <section className="noir-card mb-4"><div className="flex items-center gap-3"><h2 className="font-semibold">Inteligência artificial</h2><span className="text-xs px-2 py-1 rounded-full" style={{ background: status?.state === "ready" ? "#34d39918" : "#f59e0b18", color: status?.state === "ready" ? "#34d399" : "#f59e0b" }}>{status?.activeProvider ?? "verificando"}</span></div>
      <Row title="Provider" description={provider === "local" ? "Processamento local" : provider === "mock" ? "Resposta local simulada" : "Processamento por serviço externo"}><select className="noir-input" value={provider} onChange={async e => { const next = e.target.value as NoirSettings["aiProvider"]; await updateSettings({ aiProvider: next }); setFeedback(""); if (next === "local") await refreshLocal(); }}>{Object.entries(providerLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Row>
      {provider === "local" && <><p className="text-xs py-3" style={{ color: ollama?.state === "ready" ? "#34d399" : "#f59e0b" }}>{localExplanation}</p><Row title="Modelo local" description={`${ollama?.models.length ?? 0} modelo(s) detectado(s)`}><select className="noir-input max-w-72" value={settings.ollamaModel} onChange={e => void updateSettings({ ollamaModel: e.target.value })}><option value="">Selecione um modelo</option>{ollama?.models.map(model => <option key={model.name} value={model.name}>{model.name}</option>)}</select></Row><div className="flex gap-2 mt-4"><button disabled={busy} className="noir-secondary-button" onClick={() => void refreshLocal()}>Atualizar lista</button><button disabled={busy || !settings.ollamaModel || !ollama?.running} className="noir-primary-button" onClick={() => void action(() => AIService.testConnection("local"), "Modelo local respondeu corretamente.")}>Testar modelo</button></div></>}
      {modelField && provider !== "local" && <Row title="Modelo" description="Nome configurável; disponibilidade depende do provider"><input className="noir-input w-64" value={settings[modelField]} onChange={e => void updateSettings({ [modelField]: e.target.value })}/></Row>}
      {remote && <div className="py-4"><label className="text-sm font-medium block mb-2">Chave de API do {providerLabels[provider]}</label><div className="flex flex-wrap gap-2"><input type={showKey ? "text" : "password"} value={key} onChange={e => setKey(e.target.value)} autoComplete="off" placeholder={configured ? "Credencial protegida configurada" : "Cole a chave"} className="noir-input flex-1 min-w-56"/><button className="noir-secondary-button" onClick={() => setShowKey(v => !v)}>{showKey ? "Ocultar" : "Mostrar"}</button><button disabled={busy || !key.trim()} className="noir-primary-button" onClick={() => void action(async () => { await AIService.saveKey(provider, key); setKey(""); }, "Chave salva com criptografia do sistema.")}>Salvar</button><button disabled={busy || !configured} className="noir-danger-button" onClick={() => void action(() => AIService.removeKey(provider), "Chave removida.")}>Remover</button></div><button disabled={busy || !configured || !settings[modelField!]} className="noir-secondary-button mt-3" onClick={() => void action(() => AIService.testConnection(provider), "Conexão validada com sucesso.")}>Testar conexão</button></div>}
      <Row title="Fallback automático" description="Se ativado: Local → Groq → OpenRouter → Mock. Pode enviar contexto para serviços externos."><Toggle value={settings.automaticFallback} onChange={v => void updateSettings({ automaticFallback: v })}/></Row>
      {provider === "local" && settings.automaticFallback && <p className="text-xs mt-3" style={{ color: "#f59e0b" }}>Privacidade: falhas locais poderão encaminhar a solicitação aos providers externos configurados.</p>}{feedback && <p role="status" className="text-xs mt-3" style={{ color: /corretamente|sucesso|salva|removida|registrado/.test(feedback) ? "#34d399" : "#f87171" }}>{feedback}</p>}
    </section>
    <section className="noir-card"><div className="flex items-center gap-3"><h2 className="font-semibold">Pesquisa na Web</h2><span className="text-xs" style={{ color: webConfigured ? "#34d399" : "#f59e0b" }}>{webProviderLabel} — {webConfigured ? "disponível" : "chave ausente"}</span></div><Row title="Ativada" description="Permite pesquisas manuais com /web"><Toggle value={settings.webSearchEnabled} onChange={v => void updateSettings({ webSearchEnabled: v })}/></Row><Row title="Pesquisa automática" description="Pesquisa somente quando a pergunta contém sinais de informação volátil"><Toggle value={settings.automaticWebSearch} onChange={v => void updateSettings({ automaticWebSearch: v })}/></Row><Row title="Provider de pesquisa" description={webProvider === "wikipedia" ? "Cobertura enciclopédica; não é a busca geral principal" : `${webProviderLabel} para busca geral`}><select className="noir-input" value={webProvider} onChange={e => { setWebKey(""); setWebFeedback(""); void updateSettings({ webSearchProvider: e.target.value as NoirSettings["webSearchProvider"] }); }}><option value="tavily">Tavily</option><option value="serper">Serper</option><option value="wikipedia">Wikipedia</option><option value="brave">Brave Search</option></select></Row><Row title="Fallback automático de pesquisa" description="Tenta outro provider configurado; Wikipedia somente em consultas enciclopédicas"><Toggle value={settings.webSearchFallback} onChange={v => void updateSettings({ webSearchFallback: v })}/></Row>
      {webNeedsKey && <div className="py-4"><label className="text-sm font-medium block mb-2">Chave {webProviderLabel}</label><div className="flex gap-2"><input type="password" autoComplete="off" value={webKey} onChange={e => setWebKey(e.target.value)} placeholder={webConfigured ? "Chave configurada" : "Cole a chave"} className="noir-input flex-1"/><button disabled={!webKey.trim() || busy} className="noir-primary-button" onClick={() => void action(async () => { await window.projectNoir?.webSearch.saveKey(webProvider as "tavily" | "serper" | "brave", webKey); setWebKey(""); setWebConfigured(true); }, "Chave salva.")}>Salvar</button><button disabled={!webConfigured || busy} className="noir-danger-button" onClick={() => void action(async () => { await window.projectNoir?.webSearch.removeKey(webProvider as "tavily" | "serper" | "brave"); setWebConfigured(false); }, "Chave removida.")}>Remover</button></div></div>}
      <button disabled={busy || !settings.webSearchEnabled || (webNeedsKey && !webConfigured)} className="noir-secondary-button mt-4" onClick={() => { setBusy(true); setWebFeedback(""); void window.projectNoir?.webSearch.test("OpenAI").then(result => setWebFeedback(result.used ? `${result.provider} funcionando: ${result.results.length} resultado(s).` : result.reason || "Pesquisa indisponível.")).catch(e => setWebFeedback(e instanceof Error ? e.message : "Falha na pesquisa.")).finally(() => setBusy(false)); }}>Testar pesquisa</button>{webFeedback && <p className="text-xs mt-3" style={{ color: webFeedback.includes("funcionando") ? "#34d399" : "#f87171" }}>{webFeedback}</p>}
    </section>
  </div></div>;
}
